Colourize output

diff --git a/bin/keycutter b/bin/keycutter
--- a/bin/keycutter
+++ b/bin/keycutter
@@ -3,9 +3,19 @@ set -eu -o pipefail
 
 # [preview] keycutter - Create FIDO SSH keys for authentication and commit signing.
 
-# Source the following files:
 _SLF_DIR="$(readlink -f "$(dirname -- "${BASH_SOURCE[0]:-${0:A}}")/../")"
-source "${_SLF_DIR}/lib/functions"
+# Source the following files (optional):
+if [[ -f "${_SLF_DIR}/lib/functions" ]]; then
+    source "${_SLF_DIR}/lib/functions"
+else
+    log() {
+        echo "$*"
+    }
+    dir-ensure(){
+        mkdir -p "$1"
+        install -d -m "$2" "$1"
+    }
+fi
 
 # Prerequisites:
 #
@@ -37,38 +47,36 @@ source "${_SLF_DIR}/lib/functions"
 #      E.g. Don't login to your personal GitHub account from a managed laptop. 
 #
 
-
-
 usage() {
-    echo "Usage:"
-    echo "       $(basename "$0") <ssh-keytag> [--git-email <value>] [--git-name <value>] [--resident]"
-    echo
-    echo "Arguments:"
-    echo
-    echo "  ssh-keytag Required. Identifier for key (e.g. laptop@github-alexdoe)"
-    echo
-    echo "  --git-email Optional. Git user.email value to use with this key."
-    echo "  --git-name  Optional. Git user.name value to use with this key."
-    echo "  --resident  Optional. Create resident FIDO SSH key (default is non-resident)"
-    echo
-    echo "SSH Keytag format: device@service-user"
-    echo 
-    echo "  - device  : Device this ssh key resides on ( e.g. 'yubikey1', 'work-laptop', 'zfold5')"
-    echo "  - service : Service this key is used with (e.g. 'github', 'aws', 'digitalocean')"
-    echo "  - user    : Service User this SSH Key authenticates as (e.g. 'alexdoe')"
+    log "Usage:"
+    log "       $(basename "$0") <ssh-keytag> [--git-email <value>] [--git-name <value>] [--resident]"
+    log
+    log "Arguments:"
+    log
+    log "  ssh-keytag Required. Identifier for key (e.g. laptop@github-alexdoe)"
+    log
+    log "  --git-email Optional. Git user.email value to use with this key."
+    log "  --git-name  Optional. Git user.name value to use with this key."
+    log "  --resident  Optional. Create resident FIDO SSH key (default is non-resident)"
+    log
+    log "SSH Keytag format: device@service-user"
+    log 
+    log "  - device  : Device this ssh key resides on ( e.g. 'yubikey1', 'work-laptop', 'zfold5')"
+    log "  - service : Service this key is used with (e.g. 'github', 'aws', 'digitalocean')"
+    log "  - user    : Service User this SSH Key authenticates as (e.g. 'alexdoe')"
 }
 
 ## List SSH Keys
 
 ssh-keys-fido-resident(){
-  echo >&2 "Resident FIDO SSH Keys:"
+  log "Resident FIDO SSH Keys:"
   ssh-keygen -K
 }
 
 ssh-keys-fido-non-resident(){
   local base_config_dir="${KEYCUTTER_BASE_CONFIG_DIR:-"${HOME}/.keycutter"}"
   local ssh_key_dir="${KEYCUTTER_SSH_KEY_DIR:-"${base_config_dir}/ssh/keys"}"
-  echo >&2 "Non-resident FIDO SSH Keys:"
+  log >&2 "Non-resident FIDO SSH Keys:"
   grep -l "sk-" "$ssh_key_dir"/*.pub
 }
 
@@ -94,9 +102,9 @@ ssh-key-create() {
         return 1
     fi
     
-    echo "Generating FIDO SSH key: $ssh_key_path"
+    log "Generating FIDO SSH key: $ssh_key_path"
     if ! [[ -f "$ssh_key_path" ]]; then
-        echo "Creating directory: $(dirname "$ssh_key_path")"
+        log "Create directory: $(dirname "$ssh_key_path")"
         dir-ensure "$(dirname "$ssh_key_path")" 0700
     fi
 
@@ -104,22 +112,21 @@ ssh-key-create() {
     # XXX 1. First use of key must require PIN to unlock key
     # XXX 2. Key must be set to require touch to use
 
+    log "Generate FIDO SSH key: $ssh_key_path"
     ssh-keygen -t ecdsa-sk -b 521 -f "$ssh_key_path" -C "${ssh_key_tag}" $resident_key_option
-    echo "SSH key generated at $ssh_key_path"
 
-    echo "Creating symlink: ${ssh_key_path} -> ${identity}"
-    echo "This allows us to leave omit device part of SSH Keytag when referring to keyfile."
-    echo
+    log "Create symlink: ${ssh_key_path} -> ${identity}"
+    log "This allows us to leave omit device part of SSH Keytag when referring to keyfile."
     symlink="$(dirname $ssh_key_path)/${identity}"
     if [[ -L $symlink ]]; then
         # Get the current target of the symlink
         current_target=$(readlink "$symlink")
         if [[ $current_target == "$ssh_key_path" ]]; then
-            echo "No change required to symlink : $(ls -l "${symlink}" | awk '{print $9, "->", $11}' )"
+            log "No change required to symlink : $(ls -l "${symlink}" | awk '{print $9, "->", $11}' )"
             return 0
         else
             # Confirm whether user wants to overwrite the symlink
-            echo "Symlink already exists: $(ls -l "${symlink}" | awk '{print $9, "->", $11}' )"
+            log "Symlink already exists: $(ls -l "${symlink}" | awk '{print $9, "->", $11}' )"
             read -p "Do you want to overwrite the existing symlink? (Y/n) " choice
             choice=${choice:-Y}
             [[ $choice =~ ^[Yy]*$ ]] || return 0
@@ -144,20 +151,20 @@ ssh-config-create() {
     temp_file="$(mktemp)"
     # If we already have a config file for this identity
     if [[ -f $ssh_identity_path ]]; then
-        echo "SSH configuration file exists ($ssh_identity_path)"
+        log "SSH configuration file exists ($ssh_identity_path)"
         # If the ssh_key_path is not already in the file, add it
         if ! grep -qxF "$ssh_key_path" "$ssh_identity_path"; then
-            echo "Add IdentityFile $ssh_key_path to $ssh_identity_path"
+            log "Add IdentityFile $ssh_key_path to $ssh_identity_path"
             echo "IdentityFile $ssh_key_path" >> "$ssh_identity_path"
         else
-            echo "IdentityFile $ssh_key_path already in $ssh_identity_path"
+            log "IdentityFile $ssh_key_path already in $ssh_identity_path"
         fi
     else
         if ! [[ -d $(dirname "$ssh_identity_path") ]]; then
             # Create missing dirs in path
             dir-ensure "$(dirname "$ssh_identity_path")" 0700
         fi
-        echo "Create SSH configuration file $ssh_identity_path"
+        log "Create SSH configuration file $ssh_identity_path"
         cat > "$temp_file" <<-EOF
 Host $identity
   User git
@@ -175,8 +182,8 @@ EOF
     grep -qxF "$include_str" "${HOME}/.ssh/config" || {
         # Backup the original file
         cp "${HOME}/.ssh/config" "${HOME}/.ssh/config.replaced_by_keycutter.$(date +%s)"
-        temp_file="$(mktemp)"               # Create a temp file
-        echo "$include_str" > "$temp_file"  # Prepend the Include line to temp file
+        temp_file="$(mktemp)"                     # Create a temp file
+        echo "$include_str" > "$temp_file"        # Prepend the Include line to temp file
         cat "${HOME}/.ssh/config" >> "$temp_file" # Append original file to temp file
         mv "$temp_file" "${HOME}/.ssh/config"     # Move temp file to original location
     }
@@ -231,22 +238,22 @@ git-config-create() {
     local git_config_keycutter_path="${git_config_dir}/gitconfig-keycutter"
 
     if ! [[ -d $git_config_dir ]]; then
-        echo "Creating directory: ${git_config_dir}"
+        log "Create directory: ${git_config_dir}"
         dir-ensure "${git_config_dir}" 0700
     fi
 
     if ! git --no-pager config --global --get-regexp "^include\.path$" | grep -q "${git_config_keycutter_path}"; then
-        echo "Add include.path to global git config: ${git_config_keycutter_path}"
+        log "Add include.path to global git config: ${git_config_keycutter_path}"
         git config --global --add include.path "${git_config_keycutter_path}"
     fi
 
     # XXX Setup allowed_signers file for verifying ssh keys
     # XXX Decide on what email to use - do we require one to be provided? ask for it interactively?
     # XXX Ask if user already has one, and if not, ask if we should create one for them
-    echo "Add key to allowed_signers file ($git_config_allowed_signers_path) for verifying ssh keys"
-    echo "${git_user_email} namespaces=\"git\" $(cat "${ssh_key_path}.pub")" >> "$git_config_allowed_signers_path"
+    log "Add key to allowed_signers file ($git_config_allowed_signers_path) for verifying ssh keys"
+    log "${git_user_email} namespaces=\"git\" $(cat "${ssh_key_path}.pub")" >> "$git_config_allowed_signers_path"
 
-    echo "Create conditional git include in $git_config_keycutter_path"
+    log "Create conditional git include in $git_config_keycutter_path"
     git config \
       --file "${git_config_keycutter_path}" \
       --replace "includeIf.hasconfig:remote.*.url:git@${identity}:*/**".path \
@@ -254,11 +261,11 @@ git-config-create() {
 
     local git_config_identity_dir="$(dirname "$git_config_identity_path")"
     if ! [[ -d "$git_config_identity_dir" ]]; then
-        echo "Creating directory: ${git_config_identity_dir}"
+        log "Create directory: ${git_config_identity_dir}"
         dir-ensure "${git_config_identity_dir}" 0700
     fi
 
-    echo "Create git config for $identity in $git_config_identity_path"
+    log "Create git config for $identity in $git_config_identity_path"
     touch "$git_config_identity_path"
     git config --file "$git_config_identity_path" user.email "$git_user_email"
     git config --file "$git_config_identity_path" user.name "$git_user_name"
@@ -278,7 +285,7 @@ github-ssh-key-add() {
     local ssh_key_tag="$2"
 
     if [[ -z "$ssh_key_tag" || -z "$ssh_key_path" ]]; then 
-        echo "Error: ssh_key_tag and ssh_key_path are required."
+        log "Error: ssh_key_tag and ssh_key_path are required."
         return 1
     fi
     
@@ -287,16 +294,17 @@ github-ssh-key-add() {
     [[ $choice =~ ^[Yy]*$ ]] || return 1
 
     if github-auth; then
-        echo "Add SSH authentication key (${ssh_key_path}.pub) to GitHub"
+        log "Add SSH authentication key (${ssh_key_path}.pub) to GitHub"
         gh ssh-key add --type authentication --title "${ssh_key_tag}" "${ssh_key_path}.pub"
-        echo "Add SSH signing key (${ssh_key_path}.pub) to GitHub"
+        log "Add SSH signing key (${ssh_key_path}.pub) to GitHub"
         gh ssh-key add --type signing --title "${ssh_key_tag}" "${ssh_key_path}.pub"
-        echo
+        log
         # echo "Log out of GitHub"
         # gh auth logout # XXX Only if we logged in or requested additional scopes
-        echo "GitHub Organisations that enable or enforce SAML SSO will require additional setup."
+        log "Info: GitHub Organisations that enable or enforce SAML SSO will require additional setup."
     else
-        echo "Not uploading to key to GitHub (not authenticated)"
+        log "Error: Not uploading to key to GitHub (not authenticated)"
+        return 1
     fi
 }
 
@@ -315,9 +323,9 @@ github-auth() {
     # If user is authenticated to GitHub
     if gh_auth_token_scopes=$(gh auth status | grep scopes); then 
       if [[ $gh_auth_token_scopes =~ 'admin:public_key' ]] && [[ $gh_auth_token_scopes =~ 'admin:ssh_signing_key' ]] ; then
-        echo >&2 "GitHub CLI: Required scopes are available."
+        log >&2 "GitHub CLI: Required scopes are available."
       else
-        echo >&2 "GitHub CLI: Necessary scopes are not available. Requesting additional scopes..."
+        log >&2 "GitHub CLI: Necessary scopes are not available. Requesting additional scopes..."
         gh auth refresh -h github.com -s admin:public_key,admin:ssh_signing_key
       fi
     fi
@@ -371,7 +379,7 @@ create() {
                 if [[ -z $ssh_key_tag ]]; then
                     ssh_key_tag="$1"
                 else
-                    echo "Error: Invalid option $1"
+                    log "Error: Invalid option $1"
                     usage
                     exit 1
                 fi
@@ -402,13 +410,13 @@ create() {
     # Ensure base config directory exists and has correct permissions
     dir-ensure "$base_config_dir" 0700
 
-    echo "Create FIDO SSH Key for $ssh_key_tag"
+    log "Create FIDO SSH Key for $ssh_key_tag"
     ssh-key-create "$ssh_key_path" "$ssh_key_tag" "$identity"
 
-    echo -n "Start SSH Agent... "
+    log -n "Start SSH Agent... "
     eval "$(ssh-agent -s)"
 
-    echo -n "Add key to SSH Agent... "
+    log -n "Add key to SSH Agent... "
     ssh-add "$ssh_key_path"
 
     # Configure git to use the SSH Key for commit signing for relevant repos
@@ -417,7 +425,7 @@ create() {
     #   $git_identity_dir
     #
     # When the remote url include's the SSH Keytags "Identity Part"
-    echo "Configure git to use the SSH Key for commit/tag signing for relevant repos"
+    log "Configure git to use the SSH Key for commit/tag signing for relevant repos"
     git-config-create "$git_config_dir" "$ssh_key_path" "$identity" "$git_user_email" "$git_user_name"
 
     shopt -s nocasematch  # Enable case-insensitive pattern matching
@@ -428,14 +436,14 @@ create() {
       # e.g. `ssh github-alexdoe`
       ssh-config-create "$ssh_identity_path" "$ssh_key_path" "$identity"
       # Upload public key to GitHub for auth and commit signing
-      echo "Add SSH key to GitHub for auth and commit/tag signing: $ssh_key_path"
+      log "Add SSH key to GitHub for auth and commit/tag signing: $ssh_key_path"
       github-ssh-key-add "$ssh_key_path" "$ssh_key_tag"
     else 
-        echo "Skip GitHub specific setup - SSH Keytag identity part doesn't start with 'github-' or 'gh-'."
+        log "Skip GitHub specific setup - SSH Keytag identity part doesn't start with 'github-' or 'gh-'."
     fi
     shopt -u nocasematch  # Disable case-insensitive pattern matching
 
-    echo "Setup complete for key: $ssh_key_tag"
+    log "Setup complete for key: $ssh_key_tag"
 }
 
 list() {
@@ -451,5 +459,3 @@ if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
         create "$@"
     fi
 fi
-
-
